### ISSUE TITLE
Bugs with parsing some IPs/subnets

### ISSUE THREAD

**Issue by cybercats-team** [gwkunze/IpAddress#1]
Hi!

"Invalid address" address exception is thrown for some subnets (like 255.255.255.255/32).
That because those networks splits incorrectly (for ex 255.255.255.255/32 split onto 255.255 + 255.255/32 instead of 255.255.255.255 + 32) due the invalid regular expression in Subnet::fromString method. You've forgot to add slashes to dots ;) Below, you can see the corrected code. I hope, you will include it to nearest releases :)

```
public static function fromString($string)
    {
        $string = trim($string);

        if(preg_match("/^(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s*((nm|netmask)\\s*)?(\\d+\\.\\d+\\.\\d+\\.\\d+)$/", $string, $m)) {
            return new self($m[1], $m[4]);
        }

        if(preg_match("~^(\\d+\\.\\d+\\.\\d+\\.\\d+)/(\\d+)$~", $string, $m)) {
            return self::fromCidr($m[1], (int)$m[2]);
        }

        throw new InvalidFormatException("Unknown Subnet format");
    }
```

**Comment by gwkunze** [comment]
Thanks for finding this! I'm amazed it hasn't lead to problems earlier.
